- hosts: web
  tasks:
    - name: verif presence apache
      package:
        name: apache2
        state: present
    - name: ajout page index.html
      file:
        dest: /var/www/html/index.html
        src: files/index.html
        owner: root
        group: root
        mode: 0644
    - name: maj page 000-default.conf
      files:
        dest: /etc/apache2/sites-available/000-default.conf
        src: files/site.conf
        owner: root
        group: root
        mode: 0644
    - name: maj port 8080 listen
      files:
        dest: /etc/apache2/ports.conf
        src: files/ports.conf
        owner: root
        group: root
        mode: 0644
    - name: démarrage apache
      service:
        name: "apache2"
        state: started
        enabled: yes
